# Generated by Django 2.2.9 on 2020-01-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tesla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField()),
                ('releaseDate', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
            ],
        ),
    ]
